// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXpBxM_HU571fTfWHljJ1ObG9JpYDdBOQ',
    appId: '1:638558893813:android:b6031f09f3bcabba56b7bc',
    messagingSenderId: '638558893813',
    projectId: 'spa-ceylon-app',
    storageBucket: 'spa-ceylon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUTqHIKAES1FTZKV0eC2LL5MaHwV2a-PQ',
    appId: '1:638558893813:ios:383b2320f8bdff6956b7bc',
    messagingSenderId: '638558893813',
    projectId: 'spa-ceylon-app',
    storageBucket: 'spa-ceylon-app.firebasestorage.app',
    iosBundleId: 'com.example.spaCeylon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUTqHIKAES1FTZKV0eC2LL5MaHwV2a-PQ',
    appId: '1:638558893813:ios:383b2320f8bdff6956b7bc',
    messagingSenderId: '638558893813',
    projectId: 'spa-ceylon-app',
    storageBucket: 'spa-ceylon-app.firebasestorage.app',
    iosBundleId: 'com.example.spaCeylon',
  );
}
